Repository WildCodeSchool/fl-lyonnais-api, pull requests merged in 2020-07, with the labels that each got.

#15 Feature/tag : Remplir la base de donner avec les tags et création des routes
  api.rest
  controllers/freelances.controller.js
  controllers/tags.controller.js
  controllers/users.controller.js
  migrations/20200629161930-add-500-skills.js
  migrations/20200630144302-add-some-example-on-the-table-for-testing.js
  migrations/20200701140850-add-tags-for-each-freelancer-for-testing.js
  migrations/sqls/20200629161930-add-500-skills-down.sql
  migrations/sqls/20200629161930-add-500-skills-up.sql
  migrations/sqls/20200630144302-add-some-example-on-the-table-for-testing-down.sql
  migrations/sqls/20200630144302-add-some-example-on-the-table-for-testing-up.sql
  migrations/sqls/20200701140850-add-tags-for-each-freelancer-for-testing-down.sql
  migrations/sqls/20200701140850-add-tags-for-each-freelancer-for-testing-up.sql
  models/freelance.model.js
  models/tag.model.js
  models/user.model.js
  routes/freelances.routes.js
  routes/tags.routes.js
  routes/users.routes.js
  server.js
  tests/freelances-endpoints.js
  tests/tags-endpoints.test.js
  tests/users-endpoints.test.js
Labels: Correction done

#14 Feature3
  controllers/freelances.controller.js
Labels: To Be Reviewed

#18 Feature/email
  .email.js
  .env.sample
  api.rest
  controllers/freelances.controller.js
  controllers/users.controller.js
  models/user.model.js
  package-lock.json
  package.json
  server.js
  tests/users-endpoints.test.js
Labels: Correction done

#22 Features/us8
  .env.sample
  controllers/freelances.controller.js
  controllers/tags.controller.js
  migrations/20200704185500-add-some-reference-for-testing.js
  migrations/20200707100024-addRandomIdToFreelances.js
  migrations/20200708121045-addSettingsTable.js
  migrations/sqls/20200704185500-add-some-reference-for-testing-down.sql
  migrations/sqls/20200704185500-add-some-reference-for-testing-up.sql
  migrations/sqls/20200707100024-addRandomIdToFreelances-down.sql
  migrations/sqls/20200707100024-addRandomIdToFreelances-up.sql
  migrations/sqls/20200708121045-addSettingsTable-down.sql
  migrations/sqls/20200708121045-addSettingsTable-up.sql
  models/freelance.model.js
  models/tag.model.js
  package-lock.json
  package.json
  routes/freelances.routes.js
  routes/tags.routes.js
  test.rest
  tmp/weekNumber.txt
  weekNumber.txt
Labels: Reviewed

#24 Features/us6
  .email.js
  .env.sample
  controllers/freelances.controller.js
  controllers/users.controller.js
  docs/swagger.yaml
  middlewares/handleImageUpload.js
  migrations/20200708144037-add-is-deleted.js
  migrations/sqls/20200708144037-add-is-deleted-down.sql
  migrations/sqls/20200708144037-add-is-deleted-up.sql
  models/address.model.js
  models/freelance.model.js
  models/freelance_reference.model.js
  models/freelance_tag.model.js
  models/reference.model.js
  models/user.model.js
  package-lock.json
  package.json
  routes/freelances.routes.js
  server.js
  test.rest
  tests/freelance-endpoints.js
  tests/freelances-endpoints.js
  tmp/weekNumber.txt
Labels: Reviewed

#25 Hot fix
  .env.sample
  controllers/auth.controller.js
  controllers/freelances.controller.js
  controllers/users.controller.js
  middlewares/extractToken.js
  middlewares/requireAuth.js
  migrations/20200709135745-moveIsDeletedToUsers.js
  migrations/sqls/20200709135745-moveIsDeletedToUsers-down.sql
  migrations/sqls/20200709135745-moveIsDeletedToUsers-up.sql
  models/freelance.model.js
  models/user.model.js
  package-lock.json
  package.json
  routes/freelances.routes.js
  server.js
  test.rest
Labels: To Be Reviewed

#28 Features/us5 image
  .gitignore
  controllers/freelances.controller.js
  middlewares/handleImageUpload.js
  migrations/20200710131021-change-the-type-of-last-modification-date.js
  migrations/sqls/20200710131021-change-the-type-of-last-modification-date-down.sql
  migrations/sqls/20200710131021-change-the-type-of-last-modification-date-up.sql
  models/freelance.model.js
  models/freelance_reference.model.js
  models/freelance_tag.model.js
  models/user.model.js
  routes/freelances.routes.js
  server.js
  tests/freelance-endpoints.js
  uploads/.gitkeep
Labels: To Be Reviewed

#27 Features/us6
  controllers/freelances.controller.js
  models/freelance.model.js
  routes/freelances.routes.js
  test.rest
Labels: To Be Reviewed

#31 Features/search2
  controllers/auth.controller.js
  controllers/freelances.controller.js
  middlewares/extractToken.js
  middlewares/requireAuth.js
  models/freelance.model.js
  models/user.model.js
  package-lock.json
  package.json
  routes/freelances.routes.js
  server.js
  test.rest
  tests/users-endpoints.js
Labels: To Be Reviewed

#33 Fix/email
  .env.sample
  controllers/users.controller.js
  migrations/20200720074142-removeNotNullFieldFlagsInAddressTable.js
  migrations/sqls/20200720074142-removeNotNullFieldFlagsInAddressTable-down.sql
  migrations/sqls/20200720074142-removeNotNullFieldFlagsInAddressTable-up.sql
  package-lock.json
Labels: Reviewed

#36 Fix/search
  controllers/freelances.controller.js
  models/freelance.model.js
Labels: Reviewed

#37 fix
  controllers/freelances.controller.js
  migrations/20200721094906-validateAllTestUsers.js
  migrations/sqls/20200721094906-validateAllTestUsers-down.sql
  migrations/sqls/20200721094906-validateAllTestUsers-up.sql
  models/freelance.model.js
Labels: Reviewed

#39 Email validation fix
  controllers/freelancer.controller.js
  controllers/users.controller.js
  migrations/20200727101813-delete-some-test-profiles.js
  migrations/sqls/20200727101813-delete-some-test-profiles-down.sql
  migrations/sqls/20200727101813-delete-some-test-profiles-up.sql
  models/freelancer.model.js
  models/user.model.js
  routes/freelancer.routes.js
Labels: Reviewed

#43 Deploy
  DEPLOY.md
Labels: Reviewed
